const now = Date.now();
const minutes = (value) => value * 60 * 1000;

export const demoStores = [
  {
    id: "seongsu",
    name: "칠링 성수점",
    isOpen: true,
    layoutWidth: 140,
    layoutHeight: 220,
    activeTimerCount: 9,
    urgentCount: 1,
    overdueCount: 1,
    refillReminderCount: 1,
    todayHookahCount: 37,
    averageScore: 4.6,
    lastSeenAt: new Date(now - 12_000).toISOString(),
    updatedAt: new Date(now - 12_000).toISOString(),
  },
  {
    id: "undercity",
    name: "언더시티",
    isOpen: true,
    layoutWidth: 180,
    layoutHeight: 240,
    activeTimerCount: 6,
    urgentCount: 0,
    overdueCount: 0,
    refillReminderCount: 0,
    todayHookahCount: 18,
    averageScore: 4.3,
    lastSeenAt: new Date(now - 32_000).toISOString(),
    updatedAt: new Date(now - 32_000).toISOString(),
  },
];

export const demoTablesByStore = {
  seongsu: [
    { id: "table-1", name: "테이블 1", x: 5.14, y: 9.65 },
    { id: "table-2", name: "테이블 2", x: 5.69, y: 45.4 },
    { id: "table-3", name: "테이블 3", x: 6.27, y: 71.17 },
    { id: "table-4", name: "테이블 4", x: 82.56, y: 8.74 },
    { id: "table-5", name: "테이블 5", x: 83.65, y: 46.22 },
    { id: "table-6", name: "테이블 6", x: 8.04, y: 126.3 },
    { id: "table-7", name: "테이블 7", x: 41.9, y: 126.28 },
    { id: "table-8", name: "테이블 8", x: 70.37, y: 125.34 },
    { id: "table-9", name: "테이블 9", x: 103.57, y: 126.44 },
    { id: "table-temp", name: "간이 테이블", x: 48.42, y: 83.72 },
  ],
  undercity: [
    { id: "preset-undercity-table-1", name: "테이블 1", x: 11.43, y: 3.08 },
    { id: "preset-undercity-table-2", name: "테이블 2", x: 11.79, y: 30.37 },
    { id: "preset-undercity-table-3", name: "테이블 3", x: 14.24, y: 60.22 },
    { id: "preset-undercity-table-4", name: "테이블 4", x: 12.42, y: 85.54 },
    { id: "preset-undercity-table-5", name: "테이블 5", x: 2, y: 178.38 },
    { id: "preset-undercity-table-6", name: "테이블 6", x: 47.51, y: 178.82 },
    { id: "preset-undercity-table-7", name: "테이블 7", x: 92.18, y: 178.74 },
    { id: "preset-undercity-table-8", name: "테이블 8", x: 135.24, y: 178.52 },
    { id: "preset-undercity-table-9", name: "테이블 9", x: 109.78, y: 122.72 },
  ],
};

export const demoTimersByStore = {
  seongsu: [
    {
      id: "timer-seongsu-1",
      tableId: "table-1",
      tableName: "테이블 1",
      currentStageKey: "maintenanceTime",
      currentStageLabel: "숯 털기/1개 올림",
      startedAt: new Date(now - minutes(28)).toISOString(),
      servedAt: new Date(now - minutes(18)).toISOString(),
      scheduledServedAt: new Date(now - minutes(18)).toISOString(),
      nextTaskAt: new Date(now + minutes(2)).toISOString(),
      status: "normal",
      updatedAt: new Date(now - 10_000).toISOString(),
    },
    {
      id: "timer-seongsu-2",
      tableId: "table-2",
      tableName: "테이블 2",
      currentStageKey: "extraCoalFlip",
      currentStageLabel: "숯 1개 뒤집기",
      startedAt: new Date(now - minutes(42)).toISOString(),
      servedAt: new Date(now - minutes(32)).toISOString(),
      scheduledServedAt: new Date(now - minutes(32)).toISOString(),
      nextTaskAt: new Date(now + 42_000).toISOString(),
      status: "urgent",
      isUrgent: true,
      updatedAt: new Date(now - 6_000).toISOString(),
    },
    {
      id: "timer-seongsu-3",
      tableId: "table-3",
      tableName: "테이블 3",
      currentStageKey: "finishThree",
      currentStageLabel: "시샤 히팅 시작",
      startedAt: new Date(now - minutes(12)).toISOString(),
      scheduledServedAt: new Date(now + minutes(4)).toISOString(),
      nextTaskAt: new Date(now - 70_000).toISOString(),
      status: "overdue",
      needsConfirm: true,
      isOverdue: true,
      updatedAt: new Date(now - 2_000).toISOString(),
    },
    {
      id: "timer-seongsu-4",
      tableId: "table-4",
      tableName: "테이블 4",
      currentStageKey: "refill",
      currentStageLabel: "후카 추가 추천",
      startedAt: new Date(now - minutes(85)).toISOString(),
      servedAt: new Date(now - minutes(73)).toISOString(),
      nextTaskAt: new Date(now + minutes(11)).toISOString(),
      status: "refill",
      needsRefill: true,
      updatedAt: new Date(now - 8_000).toISOString(),
    },
    {
      id: "timer-seongsu-5",
      tableId: "table-5",
      tableName: "테이블 5",
      currentStageKey: "replaceCoal",
      currentStageLabel: "숯 1개 교체",
      startedAt: new Date(now - minutes(68)).toISOString(),
      servedAt: new Date(now - minutes(55)).toISOString(),
      nextTaskAt: new Date(now + minutes(8)).toISOString(),
      status: "normal",
      updatedAt: new Date(now - 12_000).toISOString(),
    },
  ],
  undercity: [
    {
      id: "timer-undercity-1",
      tableId: "preset-undercity-table-1",
      tableName: "테이블 1",
      currentStageKey: "maintenanceTime",
      currentStageLabel: "숯 털기/1개 올림",
      startedAt: new Date(now - minutes(31)).toISOString(),
      servedAt: new Date(now - minutes(21)).toISOString(),
      nextTaskAt: new Date(now + minutes(9)).toISOString(),
      status: "normal",
      updatedAt: new Date(now - 30_000).toISOString(),
    },
    {
      id: "timer-undercity-2",
      tableId: "preset-undercity-table-2",
      tableName: "테이블 2",
      currentStageKey: "served",
      currentStageLabel: "후카 나감",
      startedAt: new Date(now - minutes(8)).toISOString(),
      scheduledServedAt: new Date(now + minutes(4)).toISOString(),
      nextTaskAt: new Date(now + minutes(4)).toISOString(),
      status: "normal",
      updatedAt: new Date(now - 18_000).toISOString(),
    },
  ],
};
